spring:
  application:
    name: Question-Service

  datasource:
    url: jdbc:mysql://localhost:3306/question_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



